apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: userservice

  template:
    metadata:
      labels:
        app: userservice

    spec:
      containers:
        - name: userservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: 8080